# Generated by Django 5.2.17 on 2026-09-02 16:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("notebook", "Notebook"),
                            ("printer", "Printer"),
                            ("server", "Server"),
                            ("router", "Router"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("asset_tag", models.CharField(blank=True, max_length=120)),
                ("operating_system", models.CharField(blank=True, max_length=120)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("acquired_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_maintenance", "Under maintenance"),
                            ("retired", "Retired"),
                            ("lost", "Lost"),
                            ("sold", "Sold"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["customer__name", "type", "manufacturer", "model"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("cpu", "CPU"),
                            ("ram", "RAM"),
                            ("storage", "Storage"),
                            ("motherboard", "Motherboard"),
                            ("gpu", "GPU"),
                            ("power_supply", "Power supply"),
                            ("battery", "Battery"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("capacity", models.CharField(blank=True, max_length=120)),
                ("specifications", models.JSONField(blank=True, default=dict)),
                ("installed_at", models.DateField(blank=True, null=True)),
                ("removed_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="inventory.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["equipment", "component_type", "installed_at"],
            },
        ),
    ]
