# Generated by Django 5.2.17 on 2026-09-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentcomponent",
            name="source_work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installed_components",
                to="workorders.workorder",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["customer"], name="equipment_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["type"], name="equipment_type_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["status"], name="equipment_status_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["serial_number"], name="equipment_serial_idx"),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["asset_tag"], name="equipment_asset_tag_idx"),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_tag", ""), _negated=True),
                fields=("customer", "asset_tag"),
                name="equipment_asset_tag_unique_per_customer",
            ),
        ),
        migrations.AddIndex(
            model_name="equipmentcomponent",
            index=models.Index(fields=["equipment"], name="component_equipment_idx"),
        ),
        migrations.AddIndex(
            model_name="equipmentcomponent",
            index=models.Index(fields=["component_type"], name="component_type_idx"),
        ),
        migrations.AddIndex(
            model_name="equipmentcomponent",
            index=models.Index(
                fields=["equipment", "component_type", "removed_at"],
                name="component_current_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipmentcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("installed_at__isnull", True),
                    ("removed_at__isnull", True),
                    ("removed_at__gte", models.F("installed_at")),
                    _connector="OR",
                ),
                name="equipment_component_removed_after_installed",
            ),
        ),
    ]
