# Generated by Django 5.2.17 on 2026-09-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0003_configurable_equipment_catalogs"),
        ("workorders", "0004_configurable_status_and_payment_method"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="componenttype",
            name="component_type_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="equipment",
            name="equipment_customer_idx",
        ),
        migrations.RemoveIndex(
            model_name="equipment",
            name="equipment_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="equipmentcomponent",
            name="component_equipment_idx",
        ),
        migrations.RemoveIndex(
            model_name="equipmentcomponent",
            name="component_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="equipmenttype",
            name="equipment_type_slug_idx",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipments",
                to="customers.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(fields=["customer", "status"], name="equipment_customer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="equipmentcomponent",
            index=models.Index(
                condition=models.Q(("removed_at__isnull", True)),
                fields=["equipment", "installed_at"],
                name="component_cur_installed_idx",
            ),
        ),
    ]
