# Generated by Django 5.2.17 on 2026-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_componenttype_component_type_slug_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={"ordering": ["manufacturer", "model", "asset_tag"]},
        ),
        migrations.AlterModelOptions(
            name="equipmentcomponent",
            options={"ordering": ["equipment_id", "component_type_id", "installed_at"]},
        ),
    ]
