# Generated by Django 5.2.17 on 2026-09-02 16:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=120)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("storage", "Storage"),
                            ("memory", "Memory"),
                            ("battery", "Battery"),
                            ("power_supply", "Power supply"),
                            ("peripheral", "Peripheral"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "default_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "default_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="part_name_idx"),
                    models.Index(fields=["category"], name="part_category_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_cost__isnull", True),
                            ("default_cost__gte", 0),
                            _connector="OR",
                        ),
                        name="part_default_cost_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("default_price__isnull", True),
                            ("default_price__gte", 0),
                            _connector="OR",
                        ),
                        name="part_default_price_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preventive", "Preventive"),
                            ("corrective", "Corrective"),
                            ("software", "Software"),
                            ("hardware", "Hardware"),
                            ("backup", "Backup"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recommended_interval_value",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "recommended_interval_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "Days"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="service_type_slug_idx"),
                    models.Index(fields=["is_recurring"], name="service_type_recurring_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_recurring", True),
                                ("recommended_interval_value__gt", 0),
                                ("recommended_interval_value__isnull", False),
                                models.Q(("recommended_interval_unit", ""), _negated=True),
                            ),
                            ("is_recurring", False),
                            _connector="OR",
                        ),
                        name="service_type_recurring_interval_valid",
                    )
                ],
            },
        ),
    ]
