# Generated by Django 5.2.17 on 2026-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_configurable_catalog_categories"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="part",
            name="part_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="partcategory",
            name="part_category_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentmethod",
            name="payment_method_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicecategory",
            name="service_category_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicetype",
            name="service_type_slug_idx",
        ),
    ]
