# Generated by Django 5.2.17 on 2026-09-02 16:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrderNumberSequence",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
                ),
                ("current_number", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Work order number sequence",
                "verbose_name_plural": "Work order number sequences",
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveBigIntegerField(editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("problem_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("awaiting_diagnosis", "Awaiting diagnosis"),
                            ("awaiting_customer", "Awaiting customer"),
                            ("awaiting_parts", "Awaiting parts"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("service_description", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="inventory.equipment",
                    ),
                ),
                (
                    "responsible_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at", "-number"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderBilling",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "labor_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "parts_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "discount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partial"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("pix", "Pix"),
                            ("credit_card", "Credit card"),
                            ("debit_card", "Debit card"),
                            ("bank_transfer", "Bank transfer"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "work_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing",
                        to="workorders.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("performed_at", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "labor_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_work_order_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_services",
                        to="catalog.servicetype",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_work_order_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderPart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("warranty_until", models.DateField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "installed_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_parts",
                        to="inventory.equipmentcomponent",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_usages",
                        to="catalog.part",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_work_order_parts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="workorders.workorder",
                    ),
                ),
                (
                    "work_order_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="workorders.workorderservice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("awaiting_diagnosis", "Awaiting diagnosis"),
                            ("awaiting_customer", "Awaiting customer"),
                            ("awaiting_parts", "Awaiting parts"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("changed_at", models.DateTimeField()),
                ("comment", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="workorders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work order status history",
                "ordering": ["changed_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["customer"], name="work_order_customer_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["equipment"], name="work_order_equipment_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status"], name="work_order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["opened_at"], name="work_order_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["completed_at"], name="work_order_completed_idx"),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("started_at__isnull", True),
                    ("started_at__gte", models.F("opened_at")),
                    _connector="OR",
                ),
                name="work_order_started_after_opened",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("opened_at")),
                    _connector="OR",
                ),
                name="work_order_completed_after_opened",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", True),
                    ("cancelled_at__gte", models.F("opened_at")),
                    _connector="OR",
                ),
                name="work_order_cancelled_after_opened",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    ("completed_at__isnull", False),
                    _connector="OR",
                ),
                name="work_order_completed_requires_completed_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cancelled"), _negated=True),
                    ("cancelled_at__isnull", False),
                    _connector="OR",
                ),
                name="work_order_cancelled_requires_cancelled_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderbilling",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("labor_total__isnull", True),
                    ("labor_total__gte", 0),
                    _connector="OR",
                ),
                name="wo_billing_labor_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderbilling",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parts_total__isnull", True),
                    ("parts_total__gte", 0),
                    _connector="OR",
                ),
                name="wo_billing_parts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderbilling",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__isnull", True), ("discount__gte", 0), _connector="OR"),
                name="wo_billing_discount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderbilling",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_amount__isnull", True),
                    ("total_amount__gte", 0),
                    _connector="OR",
                ),
                name="wo_billing_total_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderservice",
            index=models.Index(
                fields=["work_order", "service_type", "performed_at"],
                name="wo_service_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderservice",
            index=models.Index(fields=["service_type", "performed_at"], name="wo_service_type_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="workorderservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("labor_price__isnull", True),
                    ("labor_price__gte", 0),
                    _connector="OR",
                ),
                name="work_order_service_labor_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderpart",
            index=models.Index(fields=["work_order"], name="wo_part_work_order_idx"),
        ),
        migrations.AddIndex(
            model_name="workorderpart",
            index=models.Index(fields=["work_order_service"], name="wo_part_service_idx"),
        ),
        migrations.AddConstraint(
            model_name="workorderpart",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="work_order_part_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderpart",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__isnull", True), ("unit_cost__gte", 0), _connector="OR"),
                name="work_order_part_cost_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderpart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit_price__isnull", True),
                    ("unit_price__gte", 0),
                    _connector="OR",
                ),
                name="work_order_part_price_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderstatushistory",
            index=models.Index(
                fields=["work_order", "changed_at"],
                name="wo_history_work_order_time_idx",
            ),
        ),
    ]
