# Generated by Django 5.2.17 on 2026-09-02 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0002_initial"),
        ("workorders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "completed"),
                    ("completed_at__isnull", True),
                    _connector="OR",
                ),
                name="work_order_completed_at_only_when_completed",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "cancelled"),
                    ("cancelled_at__isnull", True),
                    _connector="OR",
                ),
                name="work_order_cancelled_at_only_when_cancelled",
            ),
        ),
    ]
