# Generated by Django 5.2.17 on 2026-09-03 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_part_part_category_idx_and_more"),
        ("customers", "0001_initial"),
        ("inventory", "0004_remove_componenttype_component_type_slug_idx_and_more"),
        ("workorders", "0004_configurable_status_and_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workorder",
            name="work_order_customer_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorder",
            name="work_order_equipment_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorder",
            name="work_order_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorderpart",
            name="wo_part_work_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorderpart",
            name="wo_part_service_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorderservice",
            name="wo_service_type_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="workorderstatus",
            name="wo_status_code_idx",
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["status", "opened_at"], name="work_order_status_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["customer", "opened_at"], name="work_order_customer_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["equipment", "opened_at"], name="work_order_equip_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="workorderpart",
            index=models.Index(
                condition=models.Q(("voided_at__isnull", True)),
                fields=["work_order", "created_at"],
                name="wo_part_valid_wo_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderservice",
            index=models.Index(
                condition=models.Q(("voided_at__isnull", True)),
                fields=["service_type", "performed_at"],
                name="wo_service_valid_type_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorderservice",
            index=models.Index(
                condition=models.Q(("voided_at__isnull", True)),
                fields=["work_order", "performed_at"],
                name="wo_service_valid_wo_time_idx",
            ),
        ),
    ]
